### ISSUE TITLE
fPIC option must not be removed but ignored

### ISSUE THREAD

**Issue by Manu343726** [memsharded/conan-fmt#3]
I understand that some package options are platform dependent, but removing them in platforms where the options should not apply is not the right way to handle this (imho). I have a cross-platform project using conan for 3rdParty dependencies, all the requirements written in a conanfile.txt file. Project config is broken on windows since you explicitly remove the fPIC option, but I require my fmt dependency with fPIC option. 

Switching to conanfile.py is not an option, because it would mean that conanfile.txt based project requirements is inherently broken and not cross platform. For me, what package mantainers must do is to mark the options as "no apply" and issue a warning when the option is ignored. Another way would be to declare plaform settings subsets, such as `options.linux.fPIC`, which are automatically ignored by conan if the current platform does not match the option subset.

**Comment by memsharded** [comment]
There are some reasons for the current behavior. Ignoring the fPIC option, or not applying it silently, it is a source of errors, and a model inconsistency:
- If in a package in windows the fPIC option doesn't make sense, the system should throw an error. Package consumers can't think that they are successfully setting an option that doesn't exists.
- Keeping an option will generate 2 different package IDs, that both will generate exactly the same binary, but will be 2 different packages, one for the True and other for the False option values

If the option doesn't exist in Windows, the logic thing is that it doesn't exist in the model. Conan had in the past nested options that could somewhat model such conditional configuration, but they were removed because excessive UX complexity and none real usage.

The fact that conanfile.txt does not support conditional syntax doesn't mean that they are broken, it only means that they don't provide the complete model that the conanfile.py provides. You can still use conanfile.txt for your multi-platform needs, just create some of them and use:

```bash
$ conan install -f conanfile_win.txt
# or
$ conan install -f conanfile_linux.txt
```
